// Code generated by andurel; DO NOT EDIT.

export const routes = {
  homePage: () => '/',
  passwordCreate: () => '/users/password',
  passwordEdit: (token: string) => `/users/password/${token}/edit`,
  passwordNew: () => '/users/password/new',
  passwordUpdate: () => '/users/password',
  sessionCreate: () => '/users/sign-in',
  sessionDestroy: () => '/users/sign-out',
  sessionNew: () => '/users/sign-in',
  trackingScript: () => '/t/script.js',
  websiteCreate: () => '/websites',
  websiteDashboard: (id: string) => `/websites/${id}/dashboard`,
  websiteDestroy: (id: string) => `/websites/${id}`,
  websiteEdit: (id: string) => `/websites/${id}/edit`,
  websiteIndex: () => '/websites',
  websiteNew: () => '/websites/new',
  websiteShow: (id: string) => `/websites/${id}`,
  websiteUpdate: (id: string) => `/websites/${id}`,
}
