// Package storage provides abstractions for queue interactions and default implementations.
// Code generated by andurel v1.5.1; DO NOT EDIT.
package storage

import (
	"context"
	"database/sql"

	"github.com/riverqueue/river"
	"github.com/riverqueue/river/rivertype"
)

type InsertQueue interface {
	Insert(
		ctx context.Context,
		args river.JobArgs,
		opts *river.InsertOpts,
	) (*rivertype.JobInsertResult, error)
	InsertTx(
		ctx context.Context,
		tx *sql.Tx,
		args river.JobArgs,
		opts *river.InsertOpts,
	) (*rivertype.JobInsertResult, error)
	InsertMany(
		ctx context.Context,
		params []river.InsertManyParams,
	) ([]*rivertype.JobInsertResult, error)
	InsertManyTx(
		ctx context.Context,
		tx *sql.Tx,
		params []river.InsertManyParams,
	) ([]*rivertype.JobInsertResult, error)
	InsertManyFast(ctx context.Context, params []river.InsertManyParams) (int, error)
	InsertManyFastTx(ctx context.Context, tx *sql.Tx, params []river.InsertManyParams) (int, error)
}
