// Package server provides an HTTP server with graceful shutdown capabilities.
// Code generated by andurel v1.5.1; DO NOT EDIT.
package server

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"time"
)

const (
	DevEnvironment  = "development"
	ProdEnvironment = "production"
	TestEnvironment = "testing"
)

type Shutdowner interface {
	Shutdown(ctx context.Context) error
}

type Server struct {
	srv         *http.Server
	Shutdowners []Shutdowner
}

type ServerOptions struct {
	IdleTimeout  time.Duration
	ReadTimeout  time.Duration
	WriteTimeout time.Duration
}

type ServerOption func(*ServerOptions)

func New(
	ctx context.Context,
	host string,
	port string,
	env string,
	handler http.Handler,
	shutdowners []Shutdowner,
	options ...ServerOption,
) Server {
	serverOptions := &ServerOptions{
		IdleTimeout:  120 * time.Second,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
	}
	// Apply server options if any
	for _, option := range options {
		option(serverOptions)
	}

	srv := &http.Server{
		Addr:         fmt.Sprintf("%v:%v", host, port),
		Handler:      handler,
		IdleTimeout:  serverOptions.IdleTimeout,
		ReadTimeout:  serverOptions.ReadTimeout,
		WriteTimeout: serverOptions.WriteTimeout,
		BaseContext:  func(_ net.Listener) context.Context { return ctx },
	}

	server := Server{
		srv:         srv,
		Shutdowners: shutdowners,
	}

	server.Shutdowners = append(server.Shutdowners, srv)

	return server
}

func (s *Server) Start(
	_ context.Context,
	_ string,
) error {
	if err := s.srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		return fmt.Errorf("server: listen: %w", err)
	}

	return nil
}
