// Code generated by andurel v1.4.0; DO NOT EDIT.
package validation

import (
	"database/sql"
	"net/url"
	"reflect"
	"strings"
	"time"
)

func isMissing(fieldPtr any) bool {
	switch field := fieldPtr.(type) {
	case string:
		return strings.TrimSpace(field) == ""

	case *string:
		return field == nil || strings.TrimSpace(*field) == ""

	case *sql.NullString:
		return field == nil || !field.Valid || strings.TrimSpace(field.String) == ""

	case sql.NullString:
		return !field.Valid || strings.TrimSpace(field.String) == ""

	case time.Time:
		return field.IsZero()

	case *time.Time:
		return field == nil || field.IsZero()

	case *sql.NullTime:
		return field == nil || !field.Valid || field.Time.IsZero()

	case sql.NullTime:
		return !field.Valid || field.Time.IsZero()

	case int:
		return field == 0

	case *int:
		return field == nil || *field == 0

	case int32:
		return field == 0

	case *int32:
		return field == nil || *field == 0

	case int64:
		return field == 0

	case *int64:
		return field == nil || *field == 0

	case *sql.NullInt32:
		return field == nil || !field.Valid

	case sql.NullInt32:
		return !field.Valid

	case *sql.NullInt64:
		return field == nil || !field.Valid

	case sql.NullInt64:
		return !field.Valid

	case []string:
		return len(field) == 0

	case *[]string:
		return field == nil || len(*field) == 0
	}

	value, ok := dereferencedValue(fieldPtr)
	if !ok {
		return true
	}

	switch value.Kind() {
	case reflect.String:
		return strings.TrimSpace(value.String()) == ""

	case reflect.Slice, reflect.Map:
		return value.Len() == 0
	}

	return value.IsZero()
}

func intValue(fieldPtr any) (value int64, present bool, ok bool) {
	switch field := fieldPtr.(type) {
	case int:
		return int64(field), true, true

	case *int:
		if field == nil {
			return 0, false, true
		}

		return int64(*field), true, true

	case int32:
		return int64(field), true, true

	case *int32:
		if field == nil {
			return 0, false, true
		}

		return int64(*field), true, true

	case int64:
		return field, true, true

	case *int64:
		if field == nil {
			return 0, false, true
		}

		return *field, true, true

	case sql.NullInt32:
		if !field.Valid {
			return 0, false, true
		}

		return int64(field.Int32), true, true

	case *sql.NullInt32:
		if field == nil || !field.Valid {
			return 0, false, true
		}

		return int64(field.Int32), true, true

	case sql.NullInt64:
		if !field.Valid {
			return 0, false, true
		}

		return field.Int64, true, true

	case *sql.NullInt64:
		if field == nil || !field.Valid {
			return 0, false, true
		}

		return field.Int64, true, true

	default:
		value, ok := dereferencedValue(fieldPtr)
		if !ok {
			return 0, false, false
		}

		switch value.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			return value.Int(), true, true
		default:
			return 0, false, false
		}
	}
}

func stringValue(fieldPtr any) (value string, present bool, ok bool) {
	switch field := fieldPtr.(type) {
	case *string:
		if field == nil {
			return "", false, true
		}

		return *field, strings.TrimSpace(*field) != "", true

	case string:
		return field, strings.TrimSpace(field) != "", true

	case *sql.NullString:
		if field == nil || !field.Valid {
			return "", false, true
		}

		return field.String, true, true

	case sql.NullString:
		if !field.Valid {
			return "", false, true
		}

		return field.String, true, true

	default:
		value, ok := dereferencedValue(fieldPtr)
		if !ok {
			return "", false, false
		}

		if value.Kind() != reflect.String {
			return "", false, false
		}

		str := value.String()
		return str, strings.TrimSpace(str) != "", true
	}
}

func sliceLen(fieldPtr any) (int, bool) {
	value, ok := dereferencedValue(fieldPtr)
	if !ok {
		return 0, false
	}

	if value.Kind() != reflect.Slice && value.Kind() != reflect.Array {
		return 0, false
	}

	return value.Len(), true
}

func timeValue(fieldPtr any) (time.Time, bool) {
	switch field := fieldPtr.(type) {
	case time.Time:
		if field.IsZero() {
			return time.Time{}, false
		}

		return field, true

	case *time.Time:
		if field == nil || field.IsZero() {
			return time.Time{}, false
		}

		return *field, true

	case *sql.NullTime:
		if field == nil || !field.Valid || field.Time.IsZero() {
			return time.Time{}, false
		}

		return field.Time, true

	case sql.NullTime:
		if !field.Valid || field.Time.IsZero() {
			return time.Time{}, false
		}

		return field.Time, true

	default:
		value, ok := dereferencedValue(fieldPtr)
		if !ok {
			return time.Time{}, false
		}

		switch value.Type() {
		case reflect.TypeOf(time.Time{}):
			t := value.Interface().(time.Time)
			if t.IsZero() {
				return time.Time{}, false
			}

			return t, true

		case reflect.TypeOf(sql.NullTime{}):
			t := value.Interface().(sql.NullTime)
			if !t.Valid || t.Time.IsZero() {
				return time.Time{}, false
			}

			return t.Time, true
		}

		return time.Time{}, false
	}
}

func dereferencedValue(value any) (reflect.Value, bool) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return reflect.Value{}, false
	}

	for rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return reflect.Value{}, false
		}

		rv = rv.Elem()
	}

	return rv, true
}

func requiredBool(value any) (bool, bool) {
	switch field := value.(type) {
	case bool:
		return field, true

	case *bool:
		if field == nil {
			return false, false
		}

		return *field, true

	default:
		rv, ok := dereferencedValue(value)
		if !ok || rv.Kind() != reflect.Bool {
			return false, false
		}

		return rv.Bool(), true
	}
}

func isHTTPURL(value string) bool {
	value = strings.TrimSpace(value)

	parsed, err := url.Parse(value)
	if err != nil {
		return false
	}

	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return false
	}

	return parsed.Host != ""
}
