// Code generated by andurel v1.5.1; DO NOT EDIT.
package validation

import (
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

func (b *ValidationBuilder) Required(field string, value any, message ...string) {
	validationMessage := messageOrDefault("is required", message)
	b.AddRule(field, "required", validationMessage)

	if isMissing(value) {
		b.AddField(field, "required", validationMessage)
	}
}

func (b *ValidationBuilder) RequiredWhen(condition bool, field string, value any, message ...string) {
	if condition {
		b.Required(field, value, message...)
	}
}

func (b *ValidationBuilder) MinLen(field string, value any, min int, message ...string) {
	validationMessage := messageOrDefault(fmt.Sprintf("must be at least %d characters", min), message)
	params := map[string]any{"min": min}
	b.AddRuleWithParams(field, "min", validationMessage, params)

	str, present, ok := stringValue(value)
	if !ok || !present {
		return
	}

	if utf8.RuneCountInString(str) < min {
		b.AddFieldWithParams(
			field,
			"min",
			validationMessage,
			params,
		)
	}
}

func (b *ValidationBuilder) MaxLen(field string, value any, max int, message ...string) {
	validationMessage := messageOrDefault(fmt.Sprintf("must be at most %d characters", max), message)
	params := map[string]any{"max": max}
	b.AddRuleWithParams(field, "max", validationMessage, params)

	str, present, ok := stringValue(value)
	if !ok || !present {
		return
	}

	if utf8.RuneCountInString(str) > max {
		b.AddFieldWithParams(
			field,
			"max",
			validationMessage,
			params,
		)
	}
}

func (b *ValidationBuilder) LenBetween(field string, value any, min int, max int, message ...string) {
	b.MinLen(field, value, min, message...)
	b.MaxLen(field, value, max, message...)
}

func (b *ValidationBuilder) RecommendedLenBetween(
	field string,
	min int,
	max int,
	message ...string,
) {
	b.AddRuleWithParams(
		field,
		"recommended_length",
		messageOrDefault(
			fmt.Sprintf("recommended length is between %d and %d characters", min, max),
			message,
		),
		map[string]any{"min": min, "max": max},
	)
}

func (b *ValidationBuilder) MinInt(field string, value any, min int64, message ...string) {
	validationMessage := messageOrDefault(fmt.Sprintf("must be at least %d", min), message)
	params := map[string]any{"min": min}
	b.AddRuleWithParams(field, "min", validationMessage, params)

	integer, present, ok := intValue(value)
	if !ok || !present {
		return
	}

	if integer < min {
		b.AddFieldWithParams(field, "min", validationMessage, params)
	}
}

func (b *ValidationBuilder) MaxInt(field string, value any, max int64, message ...string) {
	validationMessage := messageOrDefault(fmt.Sprintf("must be at most %d", max), message)
	params := map[string]any{"max": max}
	b.AddRuleWithParams(field, "max", validationMessage, params)

	integer, present, ok := intValue(value)
	if !ok || !present {
		return
	}

	if integer > max {
		b.AddFieldWithParams(field, "max", validationMessage, params)
	}
}

func (b *ValidationBuilder) OneOf(field string, value any, allowed ...string) {
	b.oneOf(field, value, "has an invalid value", allowed...)
}

func (b *ValidationBuilder) OneOfWithMessage(
	field string,
	value any,
	message string,
	allowed ...string,
) {
	b.oneOf(field, value, messageOrDefault("has an invalid value", []string{message}), allowed...)
}

func (b *ValidationBuilder) oneOf(field string, value any, message string, allowed ...string) {
	params := map[string]any{"allowed": allowed}
	b.AddRuleWithParams(field, "one_of", message, params)

	str, present, ok := stringValue(value)
	if !ok || !present {
		return
	}

	if slices.Contains(allowed, str) {
		return
	}

	b.AddFieldWithParams(
		field,
		"one_of",
		message,
		params,
	)
}

func (b *ValidationBuilder) URL(field string, value any, message ...string) {
	validationMessage := messageOrDefault("must be a valid URL", message)
	b.AddRule(field, "url", validationMessage)

	str, present, ok := stringValue(value)
	if !ok || !present || strings.TrimSpace(str) == "" {
		return
	}

	if !isHTTPURL(str) {
		b.AddField(field, "url", validationMessage)
	}
}

func (b *ValidationBuilder) RequiredURL(field string, value any, message ...string) {
	b.Required(field, value, message...)
	b.URL(field, value, message...)
}

func (b *ValidationBuilder) MinItems(field string, value any, min int, message ...string) {
	validationMessage := messageOrDefault(fmt.Sprintf("must contain at least %d item(s)", min), message)
	params := map[string]any{"min": min}
	b.AddRuleWithParams(field, "min_items", validationMessage, params)

	length, ok := sliceLen(value)
	if !ok {
		return
	}

	if length < min {
		b.AddFieldWithParams(
			field,
			"min_items",
			validationMessage,
			params,
		)
	}
}

func (b *ValidationBuilder) MaxItems(field string, value any, max int, message ...string) {
	validationMessage := messageOrDefault(fmt.Sprintf("must contain at most %d item(s)", max), message)
	params := map[string]any{"max": max}
	b.AddRuleWithParams(field, "max_items", validationMessage, params)

	length, ok := sliceLen(value)
	if !ok {
		return
	}

	if length > max {
		b.AddFieldWithParams(
			field,
			"max_items",
			validationMessage,
			params,
		)
	}
}

func (b *ValidationBuilder) NoBlankItems(field string, value any, message ...string) {
	validationMessage := messageOrDefault("is required", message)
	b.AddRule(field, "no_blank_items", validationMessage)

	slice, ok := dereferencedValue(value)
	if !ok {
		return
	}
	if slice.Kind() != reflect.Slice && slice.Kind() != reflect.Array {
		return
	}

	for i := 0; i < slice.Len(); i++ {
		item := slice.Index(i)

		if item.Kind() == reflect.String && strings.TrimSpace(item.String()) == "" {
			b.Add(
				normalizeField(field)+"["+strconv.Itoa(i)+"]",
				"required",
				validationMessage,
			)
		}
	}
}

func (b *ValidationBuilder) TimeBeforeOrEqual(
	startField string,
	startValue any,
	endField string,
	endValue any,
	message ...string,
) {
	validationMessage := messageOrDefault("must be before or equal to the end time", message)
	params := map[string]any{"other": normalizeField(endField)}
	b.AddRuleWithParams(startField, "before_or_equal", validationMessage, params)

	start, startOK := timeValue(startValue)
	end, endOK := timeValue(endValue)

	if !startOK || !endOK {
		return
	}

	if start.After(end) {
		b.AddFieldWithParams(
			startField,
			"before_or_equal",
			validationMessage,
			params,
		)
	}
}

func (b *ValidationBuilder) True(field string, value any, message ...string) {
	validationMessage := messageOrDefault("must be true", message)
	b.AddRule(field, "true", validationMessage)

	boolValue, ok := requiredBool(value)
	if !ok || !boolValue {
		b.AddField(field, "true", validationMessage)
	}
}

func messageOrDefault(defaultMessage string, messages []string) string {
	if len(messages) == 0 || strings.TrimSpace(messages[0]) == "" {
		return defaultMessage
	}

	return messages[0]
}
