// Package validation provides types and utilities for validating struct fields
// and collecting validation errors. It uses a builder pattern for composing
// validation rules and supports structured error reporting with field-level
// details, codes, and parameters.
// Code generated by andurel v1.4.0; DO NOT EDIT.
package validation

import "errors"

const UnknownField = "unknown"

type Validatable interface {
	Validate() error
}

type Error struct {
	Field   string         `json:"field"`
	Code    string         `json:"code"`
	Message string         `json:"message"`
	Params  map[string]any `json:"params,omitempty"`
}

type Rule struct {
	Code    string         `json:"code"`
	Message string         `json:"message"`
	Params  map[string]any `json:"params,omitempty"`
}

type Rules map[string][]Rule

type ValidationErrors []Error

func (e ValidationErrors) Error() string {
	return "validation failed"
}

func (e ValidationErrors) Empty() bool {
	return len(e) == 0
}

func (e ValidationErrors) Len() int {
	return len(e)
}

func (e ValidationErrors) ToMap() map[string]string {
	result := map[string]string{}
	for _, validationErr := range e {
		if _, exists := result[validationErr.Field]; exists {
			continue
		}
		result[validationErr.Field] = validationErr.Message
	}

	return result
}

func As(err error) (ValidationErrors, bool) {
	if err == nil {
		return nil, false
	}

	if validationErrors, ok := errors.AsType[ValidationErrors](err); ok {
		return validationErrors, true
	}

	return nil, false
}

func Validate(value any) error {
	if value == nil {
		return nil
	}

	validatable, ok := value.(Validatable)
	if !ok {
		return nil
	}

	return validatable.Validate()
}

type ValidationBuilder struct {
	errors ValidationErrors
	rules  Rules
}

func NewBuilder() *ValidationBuilder {
	return &ValidationBuilder{
		rules: Rules{},
	}
}

func (b *ValidationBuilder) Add(field, code, message string) {
	b.errors = append(b.errors, Error{
		Field:   normalizeField(field),
		Code:    code,
		Message: message,
	})
}

func (b *ValidationBuilder) AddWithParams(
	field string,
	code string,
	message string,
	params map[string]any,
) {
	b.errors = append(b.errors, Error{
		Field:   normalizeField(field),
		Code:    code,
		Message: message,
		Params:  params,
	})
}

func (b *ValidationBuilder) AddField(field string, code, message string) {
	b.Add(field, code, message)
}

func (b *ValidationBuilder) AddFieldWithParams(
	field string,
	code string,
	message string,
	params map[string]any,
) {
	b.AddWithParams(field, code, message, params)
}

func (b *ValidationBuilder) AddRule(field, code, message string) {
	b.AddRuleWithParams(field, code, message, nil)
}

func (b *ValidationBuilder) AddRuleWithParams(
	field string,
	code string,
	message string,
	params map[string]any,
) {
	field = normalizeField(field)
	if b.rules == nil {
		b.rules = Rules{}
	}

	b.rules[field] = append(b.rules[field], Rule{
		Code:    code,
		Message: message,
		Params:  copyRuleParams(params),
	})
}

func (b *ValidationBuilder) Err() error {
	if len(b.errors) == 0 {
		return nil
	}

	return b.errors
}

func (b *ValidationBuilder) Errors() ValidationErrors {
	return b.errors
}

func (b *ValidationBuilder) Rules() Rules {
	rules := make(Rules, len(b.rules))
	for field, fieldRules := range b.rules {
		fieldRulesCopy := make([]Rule, len(fieldRules))
		for i, rule := range fieldRules {
			fieldRulesCopy[i] = Rule{
				Code:    rule.Code,
				Message: rule.Message,
				Params:  copyRuleParams(rule.Params),
			}
		}
		rules[field] = fieldRulesCopy
	}

	return rules
}

func copyRuleParams(params map[string]any) map[string]any {
	if params == nil {
		return nil
	}

	paramsCopy := make(map[string]any, len(params))
	for key, value := range params {
		paramsCopy[key] = value
	}

	return paramsCopy
}

func normalizeField(field string) string {
	if field == "" {
		return UnknownField
	}

	return field
}
