// Package hypermedia provides HTML-over-the-wire page, fragment, Datastar, and SSE helpers.
// Code generated by andurel v1.4.0; DO NOT EDIT.
package hypermedia

import (
	"time"
)

const (
	DatastarKey = "datastar"
	// The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
	DefaultSseRetryDuration           = 1000 * time.Millisecond
	DefaultElementsUseViewTransitions = false
	DefaultPatchSignalsOnlyIfMissing  = false
	SelectorDatalineLiteral           = "selector "
	ModeDatalineLiteral               = "mode "
	ElementsDatalineLiteral           = "elements "
	UseViewTransitionDatalineLiteral  = "useViewTransition "
	SignalsDatalineLiteral            = "signals "
	OnlyIfMissingDatalineLiteral      = "onlyIfMissing "
)

type executeScriptOptions struct {
	EventID       string
	AutoRemove    *bool
	Attributes    []string
	RetryDuration time.Duration
}

type ExecuteScriptOption func(*executeScriptOptions)

type ElementPatchMode string

const (
	// Default value for ElementPatchMode
	// Morphs the element into the existing element.
	DefaultElementPatchMode = ElementPatchModeOuter

	// Morphs the element into the existing element.
	ElementPatchModeOuter ElementPatchMode = "outer"
	// Replaces the inner HTML of the existing element.
	ElementPatchModeInner ElementPatchMode = "inner"
	// Removes the existing element.
	ElementPatchModeRemove ElementPatchMode = "remove"
	// Replaces the existing element with the new element.
	ElementPatchModeReplace ElementPatchMode = "replace"
	// Prepends the element inside to the existing element.
	ElementPatchModePrepend ElementPatchMode = "prepend"
	// Appends the element inside the existing element.
	ElementPatchModeAppend ElementPatchMode = "append"
	// Inserts the element before the existing element.
	ElementPatchModeBefore ElementPatchMode = "before"
	// Inserts the element after the existing element.
	ElementPatchModeAfter ElementPatchMode = "after"
)

type patchElementOptions struct {
	EventID            string
	RetryDuration      time.Duration
	Selector           string
	Mode               ElementPatchMode
	UseViewTransitions bool
}

type PatchElementOption func(*patchElementOptions)

type EventType string

const (
	// An event for patching HTML elements into the DOM.
	EventTypePatchElements EventType = "datastar-patch-elements"
	// An event for patching signals.
	EventTypePatchSignals EventType = "datastar-patch-signals"
	// An event for executing scripts.
	EventTypeExecuteScript EventType = "datastar-execute-script"
	// An event for merging signals.
	EventTypeMergeSignals EventType = "datastar-merge-signals"
)

const (
	NewLine       = "\n"
	DoubleNewLine = "\n\n"
)

var (
	newLineBuf       = []byte(NewLine)
	doubleNewLineBuf = []byte(DoubleNewLine)
)

// serverSentEventData holds event configuration data for
// [SSEEventOption]s.
type serverSentEventData struct {
	Type          EventType
	EventID       string
	Data          []string
	RetryDuration time.Duration
}

// SSEEventOption modifies one server-sent event.
type SSEEventOption func(*serverSentEventData)

var (
	eventLinePrefix = []byte("event: ")
	idLinePrefix    = []byte("id: ")
	retryLinePrefix = []byte("retry: ")
	dataLinePrefix  = []byte("data: ")
)
