// Package hypermedia provides HTML-over-the-wire page, fragment, Datastar, and SSE helpers.
// Code generated by andurel v1.5.1; DO NOT EDIT.
package hypermedia

import (
	"fmt"
	"time"
)

// WithExecuteScriptEventID sets the SSE event ID for an execute-script response.
func WithExecuteScriptEventID(id string) ExecuteScriptOption {
	return func(o *executeScriptOptions) {
		o.EventID = id
	}
}

// WithExecuteScriptRetryDuration sets the SSE retry duration for an execute-script response.
func WithExecuteScriptRetryDuration(retryDuration time.Duration) ExecuteScriptOption {
	return func(o *executeScriptOptions) {
		o.RetryDuration = retryDuration
	}
}

// WithExecuteScriptAutoRemove controls whether the injected script removes itself after execution.
func WithExecuteScriptAutoRemove(autoremove bool) ExecuteScriptOption {
	return func(o *executeScriptOptions) {
		o.AutoRemove = &autoremove
	}
}

// WithExecuteScriptAttributes adds raw attributes to the injected script tag.
func WithExecuteScriptAttributes(attributes ...string) ExecuteScriptOption {
	return func(o *executeScriptOptions) {
		o.Attributes = attributes
	}
}

// WithExecuteScriptAttributeKVs adds key/value attributes to the injected script tag.
func WithExecuteScriptAttributeKVs(kvs ...string) ExecuteScriptOption {
	if len(kvs)%2 != 0 {
		panic("WithExecuteScriptAttributeKVs requires an even number of arguments")
	}
	attributes := make([]string, 0, len(kvs)/2)
	for i := 0; i < len(kvs); i += 2 {
		attribute := fmt.Sprintf(`%s="%s"`, kvs[i], kvs[i+1])
		attributes = append(attributes, attribute)
	}
	return WithExecuteScriptAttributes(attributes...)
}

// WithPatchElementsEventID sets the SSE event ID for an element patch response.
func WithPatchElementsEventID(id string) PatchElementOption {
	return func(o *patchElementOptions) {
		o.EventID = id
	}
}

// WithSelectorf formats and sets the CSS selector targeted by an element patch.
func WithSelectorf(selectorFormat string, args ...any) PatchElementOption {
	selector := fmt.Sprintf(selectorFormat, args...)
	return WithSelector(selector)
}

// WithSelector sets the CSS selector targeted by an element patch.
func WithSelector(selector string) PatchElementOption {
	return func(o *patchElementOptions) {
		o.Selector = selector
	}
}

// WithMode sets how an element patch is applied to the target.
func WithMode(merge ElementPatchMode) PatchElementOption {
	return func(o *patchElementOptions) {
		o.Mode = merge
	}
}

// WithModeOuter configures an element patch to morph the target element.
func WithModeOuter() PatchElementOption {
	return WithMode(ElementPatchModeOuter)
}

// WithModeInner configures an element patch to replace the target element's inner HTML.
func WithModeInner() PatchElementOption {
	return WithMode(ElementPatchModeInner)
}

// WithModeRemove configures an element patch to remove the target element.
func WithModeRemove() PatchElementOption {
	return WithMode(ElementPatchModeRemove)
}

// WithModeReplace configures an element patch to replace the target element.
func WithModeReplace() PatchElementOption {
	return WithMode(ElementPatchModeReplace)
}

// WithModePrepend configures an element patch to prepend inside the target element.
func WithModePrepend() PatchElementOption {
	return WithMode(ElementPatchModePrepend)
}

// WithModeAppend configures an element patch to append inside the target element.
func WithModeAppend() PatchElementOption {
	return WithMode(ElementPatchModeAppend)
}

// WithModeBefore configures an element patch to insert before the target element.
func WithModeBefore() PatchElementOption {
	return WithMode(ElementPatchModeBefore)
}

// WithModeAfter configures an element patch to insert after the target element.
func WithModeAfter() PatchElementOption {
	return WithMode(ElementPatchModeAfter)
}

// WithSelectorID targets an element patch at the element with the given ID.
func WithSelectorID(id string) PatchElementOption {
	return WithSelector("#" + id)
}

// WithViewTransitions enables browser view transitions for an element patch.
func WithViewTransitions() PatchElementOption {
	return WithUseViewTransitions(true)
}

// WithoutViewTransitions disables browser view transitions for an element patch.
func WithoutViewTransitions() PatchElementOption {
	return WithUseViewTransitions(false)
}

// WithUseViewTransitions controls browser view transitions for an element patch.
func WithUseViewTransitions(useViewTransition bool) PatchElementOption {
	return func(o *patchElementOptions) {
		o.UseViewTransitions = useViewTransition
	}
}

// WithRetryDuration sets the SSE retry duration for an element patch response.
func WithRetryDuration(retryDuration time.Duration) PatchElementOption {
	return func(o *patchElementOptions) {
		o.RetryDuration = retryDuration
	}
}

// WithSSEEventID configures an optional event ID for one server-sent event.
// The client message field [lastEventId] will be set to this value.
// If the next event does not have an event ID, the last used event ID will remain.
//
// [lastEventId]: https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/lastEventId
func WithSSEEventID(id string) SSEEventOption {
	return func(e *serverSentEventData) {
		e.EventID = id
	}
}

// WithSSERetryDuration overrides the DefaultSseRetryDuration for one server-sent event.
func WithSSERetryDuration(retryDuration time.Duration) SSEEventOption {
	return func(e *serverSentEventData) {
		e.RetryDuration = retryDuration
	}
}
