// Package hypermedia provides HTML-over-the-wire page, fragment, Datastar, and SSE helpers.
// Code generated by andurel v1.4.0; DO NOT EDIT.
package hypermedia

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/a-h/templ"
	"github.com/labstack/echo/v5"
	"github.com/valyala/bytebufferpool"
)

// patchElements sends raw HTML as a Datastar/SSE element patch.
func patchElements(c *echo.Context, elements string, opts ...PatchElementOption) error {
	c.Response().Header().Set("Cache-Control", "no-cache")
	c.Response().Header().Set("Content-Type", "text/event-stream")

	rc := http.NewResponseController(c.Response())
	if err := rc.Flush(); err != nil {
		return fmt.Errorf("hypermedia: flush patch headers: %w", err)
	}

	options := &patchElementOptions{
		EventID:       "",
		RetryDuration: DefaultSseRetryDuration,
		Selector:      "",
		Mode:          ElementPatchModeOuter,
	}
	for _, opt := range opts {
		opt(options)
	}

	sendOptions := make([]SSEEventOption, 0, 2)
	if options.EventID != "" {
		sendOptions = append(sendOptions, WithSSEEventID(options.EventID))
	}
	if options.RetryDuration > 0 {
		sendOptions = append(sendOptions, WithSSERetryDuration(options.RetryDuration))
	}

	dataRows := make([]string, 0, 4)
	if options.Selector != "" {
		dataRows = append(dataRows, SelectorDatalineLiteral+options.Selector)
	}
	if options.Mode != ElementPatchModeOuter {
		dataRows = append(dataRows, ModeDatalineLiteral+string(options.Mode))
	}
	if options.UseViewTransitions {
		dataRows = append(dataRows, UseViewTransitionDatalineLiteral+"true")
	}

	if elements != "" {
		parts := strings.SplitSeq(elements, "\n")
		for part := range parts {
			dataRows = append(dataRows, ElementsDatalineLiteral+part)
		}
	}

	if err := Send(
		c,
		EventTypePatchElements,
		dataRows,
		sendOptions...,
	); err != nil {
		return fmt.Errorf("hypermedia: send elements: %w", err)
	}

	return nil
}

// PatchHTML sends an already-rendered HTML string as a Datastar/SSE element patch.
func PatchHTML(etx *echo.Context, html string, opts ...PatchElementOption) error {
	return patchElements(etx, html, opts...)
}

// PatchComponent renders a templ component and sends it as a Datastar/SSE element patch.
func PatchComponent(etx *echo.Context, component templ.Component, opts ...PatchElementOption) error {
	html, err := RenderHTML(etx.Request().Context(), component)
	if err != nil {
		return err
	}

	return PatchHTML(etx, html, opts...)
}

// PatchFragment renders one named templ fragment and sends it as a Datastar/SSE element patch.
func PatchFragment(etx *echo.Context, component templ.Component, key any, opts ...PatchElementOption) error {
	html, err := RenderFragment(etx.Request().Context(), component, key)
	if err != nil {
		return err
	}

	return PatchHTML(etx, html, opts...)
}

// PatchFragments renders named templ fragments and sends them as a Datastar/SSE element patch.
func PatchFragments(etx *echo.Context, component templ.Component, keys []any, opts ...PatchElementOption) error {
	html, err := RenderFragments(etx.Request().Context(), component, keys...)
	if err != nil {
		return err
	}

	return PatchHTML(etx, html, opts...)
}

// RemoveElement sends a Datastar/SSE patch that removes elements matching selector.
func RemoveElement(c *echo.Context, selector string, opts ...PatchElementOption) error {
	opts = append(opts, WithSelector(selector), WithModeRemove())
	return patchElements(c, "", opts...)
}

// RemoveElementf formats a selector and sends a Datastar/SSE remove patch.
func RemoveElementf(c *echo.Context, selectorFormat string, args ...any) error {
	selector := fmt.Sprintf(selectorFormat, args...)
	return RemoveElement(c, selector)
}

// RemoveElementByID sends a Datastar/SSE remove patch for the element with id.
func RemoveElementByID(c *echo.Context, id string, opts ...PatchElementOption) error {
	return RemoveElement(c, "#"+id, opts...)
}

// DispatchCustomEvent dispatches a browser CustomEvent through a Datastar/SSE script patch.
func DispatchCustomEvent(
	c *echo.Context,
	eventName string,
	detail any,
	opts ...DispatchCustomEventOption,
) error {
	c.Response().Header().Set("Cache-Control", "no-cache")
	c.Response().Header().Set("Content-Type", "text/event-stream")

	rc := http.NewResponseController(c.Response())
	if err := rc.Flush(); err != nil {
		return fmt.Errorf("hypermedia: flush custom event headers: %w", err)
	}

	if eventName == "" {
		return errors.New("hypermedia: event name is required")
	}

	detailsJSON, err := json.Marshal(detail)
	if err != nil {
		return fmt.Errorf("hypermedia: marshal custom event detail: %v", err)
	}

	const defaultSelector = "document"
	options := dispatchCustomEventOptions{
		EventID:       "",
		RetryDuration: DefaultSseRetryDuration,
		Selector:      defaultSelector,
		Bubbles:       true,
		Cancelable:    true,
		Composed:      true,
	}

	for _, opt := range opts {
		opt(&options)
	}

	elementsJS := `[document]`
	if options.Selector != "" && options.Selector != defaultSelector {
		elementsJS = fmt.Sprintf(`document.querySelectorAll(%q)`, options.Selector)
	}

	js := fmt.Sprintf(`
const elements = %s

const event = new CustomEvent(%q, {
    bubbles: %t,
    cancelable: %t,
    composed: %t,
    detail: %s,
});

elements.forEach((element) => {
    element.dispatchEvent(event);
});
    `,
		elementsJS,
		eventName,
		options.Bubbles,
		options.Cancelable,
		options.Composed,
		string(detailsJSON),
	)

	executeOptions := make([]ExecuteScriptOption, 0)
	if options.EventID != "" {
		executeOptions = append(executeOptions, WithExecuteScriptEventID(options.EventID))
	}
	if options.RetryDuration != 0 {
		executeOptions = append(
			executeOptions,
			WithExecuteScriptRetryDuration(options.RetryDuration),
		)
	}

	return ExecuteScript(c, js, executeOptions...)
}

// PatchSignal sends one signal value as a Datastar/SSE signal patch.
func PatchSignal(c *echo.Context, key string, value any, opts ...PatchSignalsOption) error {
	return PatchSignals(c, map[string]any{key: value}, opts...)
}

// PatchSignals sends signal values as a Datastar/SSE signal patch.
func PatchSignals(c *echo.Context, signals map[string]any, opts ...PatchSignalsOption) error {
	signalsJSON, err := json.Marshal(signals)
	if err != nil {
		return fmt.Errorf("hypermedia: marshal signals: %v", err)
	}
	return patchSignalsRaw(c, signalsJSON, opts...)
}

// patchSignalsRaw sends pre-encoded signal JSON as a Datastar/SSE signal patch.
func patchSignalsRaw(c *echo.Context, signalsContents []byte, opts ...PatchSignalsOption) error {
	c.Response().Header().Set("Cache-Control", "no-cache")
	c.Response().Header().Set("Content-Type", "text/event-stream")

	rc := http.NewResponseController(c.Response())
	if err := rc.Flush(); err != nil {
		return fmt.Errorf("hypermedia: flush patch signal headers: %w", err)
	}

	options := &patchSignalsOptions{
		EventID:       "",
		RetryDuration: DefaultSseRetryDuration,
		OnlyIfMissing: false,
	}
	for _, opt := range opts {
		opt(options)
	}

	dataRows := make([]string, 0, 32)
	if options.OnlyIfMissing {
		dataRows = append(
			dataRows,
			OnlyIfMissingDatalineLiteral+strconv.FormatBool(options.OnlyIfMissing),
		)
	}
	lines := strings.SplitSeq(string(signalsContents), "\n")
	for line := range lines {
		dataRows = append(dataRows, SignalsDatalineLiteral+line)
	}

	sendOptions := make([]SSEEventOption, 0, 2)
	if options.EventID != "" {
		sendOptions = append(sendOptions, WithSSEEventID(options.EventID))
	}
	if options.RetryDuration != DefaultSseRetryDuration {
		sendOptions = append(sendOptions, WithSSERetryDuration(options.RetryDuration))
	}

	if err := Send(
		c,
		EventTypePatchSignals,
		dataRows,
		sendOptions...,
	); err != nil {
		return fmt.Errorf("hypermedia: send patch signals: %w", err)
	}
	return nil
}

// MergeSignals sends signal values as a Datastar/SSE merge-signals event.
func MergeSignals(c *echo.Context, signals map[string]any) error {
	c.Response().Header().Set("Cache-Control", "no-cache")
	c.Response().Header().Set("Content-Type", "text/event-stream")

	rc := http.NewResponseController(c.Response())
	if err := rc.Flush(); err != nil {
		return fmt.Errorf("hypermedia: flush merge signal headers: %w", err)
	}

	dataRows := make([]string, 0, len(signals))
	for key, value := range signals {
		dataRows = append(dataRows, fmt.Sprintf("%s %v", key, value))
	}

	if err := Send(
		c,
		EventTypeMergeSignals,
		dataRows,
	); err != nil {
		return fmt.Errorf("hypermedia: merge signals: %w", err)
	}

	return nil
}

// ReadSignals reads Datastar signals from a request into signals.
func ReadSignals(r *http.Request, signals any) error {
	var dsInput []byte

	if r.Method == "GET" {
		dsJSON := r.URL.Query().Get(DatastarKey)
		if dsJSON == "" {
			return nil
		}
		dsInput = []byte(dsJSON)
	}
	if r.Method != "GET" {
		buf := bytebufferpool.Get()
		defer bytebufferpool.Put(buf)
		if _, err := buf.ReadFrom(r.Body); err != nil {
			if err == http.ErrBodyReadAfterClose {
				return fmt.Errorf(
					"hypermedia: read signals after body close: %w",
					err,
				)
			}
			return fmt.Errorf("hypermedia: read signals body: %w", err)
		}
		dsInput = buf.Bytes()
	}

	if err := json.Unmarshal(dsInput, signals); err != nil {
		return fmt.Errorf("hypermedia: unmarshal signals: %v", err)
	}
	return nil
}

// Send writes one server-sent event to the response and flushes it.
func Send(c *echo.Context, eventType EventType, dataLines []string, opts ...SSEEventOption) error {
	if err := c.Request().Context().Err(); err != nil {
		return fmt.Errorf("hypermedia: request context done: %w", err)
	}

	buf, err := buildSSEEvent(eventType, dataLines, opts...)
	if err != nil {
		return err
	}
	defer bytebufferpool.Put(buf)

	if _, err := buf.WriteTo(c.Response()); err != nil {
		return fmt.Errorf("hypermedia: write SSE event: %w", err)
	}

	rc := http.NewResponseController(c.Response())
	if err := rc.Flush(); err != nil {
		return fmt.Errorf("hypermedia: flush SSE event: %w", err)
	}

	return nil
}

// buildSSEEvent encodes event metadata and data lines into SSE wire format.
func buildSSEEvent(
	eventType EventType,
	dataLines []string,
	opts ...SSEEventOption,
) (*bytebufferpool.ByteBuffer, error) {
	evt := serverSentEventData{
		Type:          eventType,
		Data:          dataLines,
		RetryDuration: DefaultSseRetryDuration,
	}

	for _, opt := range opts {
		opt(&evt)
	}

	buf := bytebufferpool.Get()

	if err := errors.Join(
		writeJustError(buf, eventLinePrefix),
		writeJustError(buf, []byte(evt.Type)),
		writeJustError(buf, newLineBuf),
	); err != nil {
		bytebufferpool.Put(buf)
		return nil, fmt.Errorf("hypermedia: write SSE event type: %w", err)
	}

	if evt.EventID != "" {
		if err := errors.Join(
			writeJustError(buf, idLinePrefix),
			writeJustError(buf, []byte(evt.EventID)),
			writeJustError(buf, newLineBuf),
		); err != nil {
			bytebufferpool.Put(buf)
			return nil, fmt.Errorf("hypermedia: write SSE id: %w", err)
		}
	}

	if evt.RetryDuration.Milliseconds() > 0 &&
		evt.RetryDuration.Milliseconds() != DefaultSseRetryDuration.Milliseconds() {
		retry := int(evt.RetryDuration.Milliseconds())
		retryStr := strconv.Itoa(retry)
		if err := errors.Join(
			writeJustError(buf, retryLinePrefix),
			writeJustError(buf, []byte(retryStr)),
			writeJustError(buf, newLineBuf),
		); err != nil {
			bytebufferpool.Put(buf)
			return nil, fmt.Errorf("hypermedia: write SSE retry: %w", err)
		}
	}

	for _, d := range evt.Data {
		if err := errors.Join(
			writeJustError(buf, dataLinePrefix),
			writeJustError(buf, []byte(d)),
			writeJustError(buf, newLineBuf),
		); err != nil {
			bytebufferpool.Put(buf)
			return nil, fmt.Errorf("hypermedia: write SSE data: %w", err)
		}
	}

	if err := writeJustError(buf, doubleNewLineBuf); err != nil {
		bytebufferpool.Put(buf)
		return nil, fmt.Errorf("hypermedia: write SSE newline: %w", err)
	}

	return buf, nil
}

// writeJustError writes bytes and returns only the write error.
func writeJustError(w io.Writer, b []byte) (err error) {
	_, err = w.Write(b)
	return err
}
