// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

// CountUsers
//
//	select count(*) from users
func (q *Queries) CountUsers(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id=$1
`

// DeleteUser
//
//	delete from users where id=$1
func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.Exec(ctx, deleteUser, id)
	return err
}

const insertUser = `-- name: InsertUser :one
insert into
    users (id, created_at, updated_at, email, email_validated_at, password, is_admin)
values
    ($1, now(), now(), $2, $3, $4, $5)
returning id, created_at, updated_at, email, email_validated_at, password, is_admin
`

type InsertUserParams struct {
	ID               uuid.UUID
	Email            string
	EmailValidatedAt pgtype.Timestamptz
	Password         []byte
	IsAdmin          bool
}

// InsertUser
//
//	insert into
//	    users (id, created_at, updated_at, email, email_validated_at, password, is_admin)
//	values
//	    ($1, now(), now(), $2, $3, $4, $5)
//	returning id, created_at, updated_at, email, email_validated_at, password, is_admin
func (q *Queries) InsertUser(ctx context.Context, db DBTX, arg InsertUserParams) (User, error) {
	row := db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.EmailValidatedAt,
		arg.Password,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailValidatedAt,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const queryPaginatedUsers = `-- name: QueryPaginatedUsers :many
select id, created_at, updated_at, email, email_validated_at, password, is_admin from users
order by created_at desc
limit $2::bigint offset $1::bigint
`

type QueryPaginatedUsersParams struct {
	Offset int64
	Limit  int64
}

// QueryPaginatedUsers
//
//	select id, created_at, updated_at, email, email_validated_at, password, is_admin from users
//	order by created_at desc
//	limit $2::bigint offset $1::bigint
func (q *Queries) QueryPaginatedUsers(ctx context.Context, db DBTX, arg QueryPaginatedUsersParams) ([]User, error) {
	rows, err := db.Query(ctx, queryPaginatedUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.EmailValidatedAt,
			&i.Password,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUserByEmail = `-- name: QueryUserByEmail :one
select id, created_at, updated_at, email, email_validated_at, password, is_admin from users where email=$1
`

// QueryUserByEmail
//
//	select id, created_at, updated_at, email, email_validated_at, password, is_admin from users where email=$1
func (q *Queries) QueryUserByEmail(ctx context.Context, db DBTX, email string) (User, error) {
	row := db.QueryRow(ctx, queryUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailValidatedAt,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const queryUserByID = `-- name: QueryUserByID :one
select id, created_at, updated_at, email, email_validated_at, password, is_admin from users where id=$1
`

// QueryUserByID
//
//	select id, created_at, updated_at, email, email_validated_at, password, is_admin from users where id=$1
func (q *Queries) QueryUserByID(ctx context.Context, db DBTX, id uuid.UUID) (User, error) {
	row := db.QueryRow(ctx, queryUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailValidatedAt,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}

const queryUsers = `-- name: QueryUsers :many
select id, created_at, updated_at, email, email_validated_at, password, is_admin from users
`

// QueryUsers
//
//	select id, created_at, updated_at, email, email_validated_at, password, is_admin from users
func (q *Queries) QueryUsers(ctx context.Context, db DBTX) ([]User, error) {
	rows, err := db.Query(ctx, queryUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.EmailValidatedAt,
			&i.Password,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
update users
    set updated_at=now(), email=$2, email_validated_at=$3, password=$4, is_admin=$5
where id = $1
returning id, created_at, updated_at, email, email_validated_at, password, is_admin
`

type UpdateUserParams struct {
	ID               uuid.UUID
	Email            string
	EmailValidatedAt pgtype.Timestamptz
	Password         []byte
	IsAdmin          bool
}

// UpdateUser
//
//	update users
//	    set updated_at=now(), email=$2, email_validated_at=$3, password=$4, is_admin=$5
//	where id = $1
//	returning id, created_at, updated_at, email, email_validated_at, password, is_admin
func (q *Queries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error) {
	row := db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailValidatedAt,
		arg.Password,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailValidatedAt,
		&i.Password,
		&i.IsAdmin,
	)
	return i, err
}
