package factories

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
	"palantir/internal/storage"
	"palantir/models"
	"time"
)

// Factory declarations below are generated by Andurel.

type EventFactory struct {
	models.EventEntity
}

type EventOption func(*EventFactory)

func BuildEvent(websiteID uuid.UUID, opts ...EventOption) models.EventEntity {
	f := &EventFactory{
		EventEntity: models.EventEntity{
			WebsiteID:   websiteID,
			Url:         faker.Word(),
			EventName:   faker.Word(),
			EventData:   json.RawMessage{},
			VisitorHash: sql.NullString{String: faker.Word(), Valid: true},
			CountryCode: sql.NullString{String: faker.Word(), Valid: true},
			CountryName: sql.NullString{String: faker.Word(), Valid: true},
			City:        sql.NullString{String: faker.Word(), Valid: true},
			Region:      sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EventEntity
}

func CreateEvent(ctx context.Context, exec storage.Executor, websiteID uuid.UUID, opts ...EventOption) (models.EventEntity, error) {
	built := BuildEvent(websiteID, opts...)

	entity := models.EventEntity{
		ID:          uuid.New(),
		CreatedAt:   time.Now(),
		WebsiteID:   built.WebsiteID,
		Url:         built.Url,
		EventName:   built.EventName,
		EventData:   built.EventData,
		VisitorHash: built.VisitorHash,
		CountryCode: built.CountryCode,
		CountryName: built.CountryName,
		City:        built.City,
		Region:      built.Region,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EventEntity{}, err
	}

	return entity, nil
}

func CreateEvents(ctx context.Context, exec storage.Executor, websiteID uuid.UUID, count int, opts ...EventOption) ([]models.EventEntity, error) {
	events := make([]models.EventEntity, 0, count)

	for i := 0; i < count; i++ {
		entity, err := CreateEvent(ctx, exec, websiteID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create event %d: %w", i+1, err)
		}
		events = append(events, entity)
	}

	return events, nil
}

func WithEventsWebsiteID(value uuid.UUID) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.WebsiteID = value
	}
}

func WithEventsUrl(value string) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.Url = value
	}
}

func WithEventsEventName(value string) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.EventName = value
	}
}

func WithEventsEventData(value json.RawMessage) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.EventData = value
	}
}

func WithEventsVisitorHash(value sql.NullString) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.VisitorHash = value
	}
}

func WithEventsCountryCode(value sql.NullString) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.CountryCode = value
	}
}

func WithEventsCountryName(value sql.NullString) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.CountryName = value
	}
}

func WithEventsCity(value sql.NullString) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.City = value
	}
}

func WithEventsRegion(value sql.NullString) EventOption {
	return func(f *EventFactory) {
		f.EventEntity.Region = value
	}
}
