package factories

import (
	"context"
	"fmt"
	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
	"palantir/internal/storage"
	"palantir/models"
	"time"
)

// Factory declarations below are generated by Andurel.

type WebsiteFactory struct {
	models.WebsiteEntity
}

type WebsiteOption func(*WebsiteFactory)

func BuildWebsite(userID uuid.UUID, opts ...WebsiteOption) models.WebsiteEntity {
	f := &WebsiteFactory{
		WebsiteEntity: models.WebsiteEntity{
			UserID: userID,
			Name:   faker.Word(),
			Domain: faker.Word(),
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.WebsiteEntity
}

func CreateWebsite(ctx context.Context, exec storage.Executor, userID uuid.UUID, opts ...WebsiteOption) (models.WebsiteEntity, error) {
	built := BuildWebsite(userID, opts...)

	entity := models.WebsiteEntity{
		ID:        uuid.New(),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
		UserID:    built.UserID,
		Name:      built.Name,
		Domain:    built.Domain,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.WebsiteEntity{}, err
	}

	return entity, nil
}

func CreateWebsites(ctx context.Context, exec storage.Executor, userID uuid.UUID, count int, opts ...WebsiteOption) ([]models.WebsiteEntity, error) {
	websites := make([]models.WebsiteEntity, 0, count)

	for i := 0; i < count; i++ {
		entity, err := CreateWebsite(ctx, exec, userID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create website %d: %w", i+1, err)
		}
		websites = append(websites, entity)
	}

	return websites, nil
}

func WithWebsitesUserID(value uuid.UUID) WebsiteOption {
	return func(f *WebsiteFactory) {
		f.WebsiteEntity.UserID = value
	}
}

func WithWebsitesName(value string) WebsiteOption {
	return func(f *WebsiteFactory) {
		f.WebsiteEntity.Name = value
	}
}

func WithWebsitesDomain(value string) WebsiteOption {
	return func(f *WebsiteFactory) {
		f.WebsiteEntity.Domain = value
	}
}
