// Package routing provides abstractions for working with routes.
// Code generated by andurel v1.5.1; DO NOT EDIT.
package routing

import "github.com/google/uuid"

// RouteOption customizes URL generation.
type RouteOption func(*routeOptions)

// Route represents routes with no URL parameters
type SimpleRoute interface {
	Name() string
	Path() string
	URL(opts ...RouteOption) string
	FullURL(base string, opts ...RouteOption) string
}

// UUIDIDRoute represents routes with a UUID ID in the URL parameter
type UUIDIDRoute interface {
	Name() string
	Path() string
	URL(id uuid.UUID, opts ...RouteOption) string
	FullURL(base string, id uuid.UUID, opts ...RouteOption) string
	GetParam() string
}

// SerialIDRoute represents routes with a serial (int32) ID in the URL parameter
type SerialIDRoute interface {
	Name() string
	Path() string
	URL(id int32, opts ...RouteOption) string
	FullURL(base string, id int32, opts ...RouteOption) string
	GetParam() string
}

// BigSerialIDRoute represents routes with a bigserial (int64) ID in the URL parameter
type BigSerialIDRoute interface {
	Name() string
	Path() string
	URL(id int64, opts ...RouteOption) string
	FullURL(base string, id int64, opts ...RouteOption) string
	GetParam() string
}

// StringIDRoute represents routes with a string ID in the URL parameter
type StringIDRoute interface {
	Name() string
	Path() string
	URL(id string, opts ...RouteOption) string
	FullURL(base string, id string, opts ...RouteOption) string
	GetParam() string
}

// ParamRoute represents routes with a single URL parameter
type ParamRoute interface {
	Name() string
	Path() string
	URL(param string, opts ...RouteOption) string
	FullURL(base string, param string, opts ...RouteOption) string
	GetParam() string
}

// ParamsRoute represents routes with multiple parameters, where Params is a struct
// with struct tags to map fields to URL parameters.
//
// Example:
//
//	type ServerSlugParams struct {
//	    Server string `param:"server"`
//	    Team   string `param:"team"`
//	}
type ParamsRoute[Params any] interface {
	Name() string
	Path() string
	URL(params Params, opts ...RouteOption) string
	FullURL(base string, params Params, opts ...RouteOption) string
}
